apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production

resources:
- ../../base
- canary.yaml   # <--- Ajout du Canary

patches:
- path: ingress-patch.yaml # Garde celui-ci pour dÃ©finir le nom de domaine (host)

images:
- name: nginx:1.23.0
  newName: nginx
  newTag: 1.23.0 # On reste sur la version stable pour l'instant
