name: Security Scan

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-analyze-scan:
    runs-on: ubuntu-latest
    permissions:
      security-events: write  # Indispensable pour l'onglet Security
      actions: read
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          scan-ref: '.'
          format: 'sarif'                 # <--- Format pour l'onglet Security
          output: 'trivy-results.sarif'   # <--- On écrit dans un fichier
          severity: 'CRITICAL,HIGH'
          exit-code: '1'                  # <--- BLOQUANT : La pipeline échoue si faille trouvée
          ignore-unfixed: true

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: always()                      # <--- IMPORTANT : Envoie le rapport même si ça plante
        with:
          sarif_file: 'trivy-results.sarif'
